import { createClient } from '@sanity/client';

// NOTE: You must provide a token with WRITE access in your .env.local
// or replace process.env.SANITY_API_TOKEN below.
const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'your-project-id',
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  apiVersion: '2023-05-03',
  useCdn: false,
  token: process.env.SANITY_API_TOKEN || 'your-write-token',
});

const newPlaces = [
  // --- FOOD & RESTAURANT (10 Entries) ---
  {
    _type: 'place',
    name: 'Andhra Spice',
    slug: { _type: 'slug', current: 'andhra-spice' },
    category: 'Food',
    placeType: 'food',
    location: 'Tirupati Center',
    budgetLevel: 'medium',
    rating: 4.5,
    reviewCount: 1200,
    description: 'Authentic Andhra meals with a fiery kick. Known for their traditional thalis.',
    interests: ['food', 'family'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Govinda Restaurant (ISKCON)',
    slug: { _type: 'slug', current: 'govinda-restaurant' },
    category: 'Food',
    placeType: 'food',
    location: 'Hare Krishna Road',
    budgetLevel: 'budget',
    rating: 4.8,
    reviewCount: 3500,
    description: 'Pure vegetarian satvik food served in a peaceful environment.',
    interests: ['food', 'spiritual'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Minerva Grand',
    slug: { _type: 'slug', current: 'minerva-grand' },
    category: 'Food',
    placeType: 'food',
    location: 'Renigunta Road',
    budgetLevel: 'premium',
    rating: 4.4,
    reviewCount: 850,
    description: 'Fine dining multi-cuisine restaurant offering a premium experience.',
    interests: ['food', 'luxury'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Plantain Leaf',
    slug: { _type: 'slug', current: 'plantain-leaf' },
    category: 'Food',
    placeType: 'food',
    location: 'Tirumala Bypass Road',
    budgetLevel: 'medium',
    rating: 4.3,
    reviewCount: 2100,
    description: 'Famous for traditional South Indian meals served on banana leaves.',
    interests: ['food', 'culture'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Pai Viceroy',
    slug: { _type: 'slug', current: 'pai-viceroy' },
    category: 'Food',
    placeType: 'food',
    location: 'Near RTC Bus Stand',
    budgetLevel: 'medium',
    rating: 4.2,
    reviewCount: 1150,
    description: 'Excellent South Indian and North Indian vegetarian options.',
    interests: ['food', 'family'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Hotel Bliss',
    slug: { _type: 'slug', current: 'hotel-bliss' },
    category: 'Food',
    placeType: 'food',
    location: 'Renigunta Road',
    budgetLevel: 'premium',
    rating: 4.5,
    reviewCount: 2200,
    description: 'A popular choice for both North Indian and South Indian delicacies.',
    interests: ['food'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Kalyan Residency Veg',
    slug: { _type: 'slug', current: 'kalyan-residency-veg' },
    category: 'Food',
    placeType: 'food',
    location: 'Tirupati Town',
    budgetLevel: 'budget',
    rating: 4.1,
    reviewCount: 900,
    description: 'Comfort food and quick tiffins for travelers.',
    interests: ['food'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Srivari Brahmotsavam Food Court',
    slug: { _type: 'slug', current: 'srivari-food-court' },
    category: 'Food',
    placeType: 'food',
    location: 'Tirumala',
    budgetLevel: 'budget',
    rating: 4.7,
    reviewCount: 5000,
    description: 'Free meals (Annadanam) provided by TTD to thousands of pilgrims daily.',
    interests: ['food', 'spiritual'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Jalpaan',
    slug: { _type: 'slug', current: 'jalpaan' },
    category: 'Food',
    placeType: 'food',
    location: 'Tirupati Center',
    budgetLevel: 'medium',
    rating: 4.4,
    reviewCount: 650,
    description: 'Modern vegetarian dining with innovative dishes and mocktails.',
    interests: ['food'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Sri Krishna Sweets',
    slug: { _type: 'slug', current: 'sri-krishna-sweets' },
    category: 'Food',
    placeType: 'food',
    location: 'Prakasam Road',
    budgetLevel: 'budget',
    rating: 4.6,
    reviewCount: 1500,
    description: 'Iconic spot for traditional Andhra sweets and quick snacks.',
    interests: ['food'],
    isMustVisit: false,
  },

  // --- SPIRITUAL PLACES ---
  {
    _type: 'place',
    name: 'Vakula Matha Temple',
    slug: { _type: 'slug', current: 'vakula-matha' },
    category: 'Spiritual',
    placeType: 'spiritual',
    location: 'Peruru',
    budgetLevel: 'budget',
    rating: 4.8,
    reviewCount: 4200,
    description: 'Dedicated to Vakula Devi, the foster mother of Lord Venkateswara.',
    history: 'A symbol of unconditional love between mother and son.',
    interests: ['spiritual'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Agastheeshwara Temple',
    slug: { _type: 'slug', current: 'agastheeshwara' },
    category: 'Spiritual',
    placeType: 'spiritual',
    location: 'Tondavada',
    budgetLevel: 'budget',
    rating: 4.6,
    reviewCount: 1800,
    description: 'Ancient Shiva temple at the confluence of three rivers.',
    history: 'Believed to have been established by Sage Agasthya.',
    interests: ['spiritual', 'history'],
    isMustVisit: true,
  },

  // --- NATURE PLACES ---
  {
    _type: 'place',
    name: 'Sri Venkateswara National Park',
    slug: { _type: 'slug', current: 'sv-national-park' },
    category: 'Nature',
    placeType: 'nature',
    location: 'Seshachalam Hills',
    budgetLevel: 'budget',
    rating: 4.7,
    reviewCount: 8500,
    description: 'Biosphere reserve known for rich biodiversity and deep valleys.',
    interests: ['nature', 'wildlife'],
    isMustVisit: true,
  },
  {
    _type: 'place',
    name: 'Tada Falls',
    slug: { _type: 'slug', current: 'tada-falls' },
    category: 'Nature',
    placeType: 'nature',
    location: 'Chittoor District',
    budgetLevel: 'budget',
    rating: 4.5,
    reviewCount: 6200,
    description: 'Beautiful multi-cascading waterfall perfect for trekking.',
    interests: ['nature', 'trekking'],
    isMustVisit: true,
  },

  // --- HERITAGE PLACES ---
  {
    _type: 'place',
    name: 'Dhyana Vignan Mandiram',
    slug: { _type: 'slug', current: 'dhyana-vignan-mandiram' },
    category: 'Heritage',
    placeType: 'culture',
    location: 'Tirupati',
    budgetLevel: 'budget',
    rating: 4.4,
    reviewCount: 950,
    description: 'Meditation center and museum housing traditional puja articles.',
    interests: ['culture', 'spiritual'],
    isMustVisit: false,
  },
  {
    _type: 'place',
    name: 'Gingee Fort',
    slug: { _type: 'slug', current: 'gingee-fort' },
    category: 'Heritage',
    placeType: 'historical',
    location: 'Tamil Nadu (Near Tirupati)',
    budgetLevel: 'budget',
    rating: 4.6,
    reviewCount: 5400,
    description: 'Impressive historical fortification known as the Troy of the East.',
    interests: ['history', 'architecture'],
    isMustVisit: true,
  },
];

async function runMigration() {
  console.log('Starting data migration to Sanity...');
  try {
    for (const place of newPlaces) {
      console.log(`Migrating: ${place.name}`);
      // Use createIfNotExists or create to add the document
      await client.createIfNotExists({
        _id: `place-${place.slug.current}`,
        ...(place as any),
      });
    }
    console.log('Migration completed successfully!');
  } catch (error) {
    console.error('Migration failed:', error);
  }
}

runMigration();
